-- MySQL Script generated by MySQL Workbench
-- Sun Nov 24 20:59:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `id` INT NOT NULL,
  `nif` INT NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone` INT NOT NULL,
  `fax` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `teléfono_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `fax_UNIQUE` (`fax` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  UNIQUE INDEX `address_UNIQUE` (`address` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`glasses` (
  `id` INT NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `grade` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `framecolor` VARCHAR(45) NOT NULL,
  `crystalcolor` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `brand_UNIQUE` (`brand` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_proveedor_idx` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `id_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `mydb`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `date_signup` INT NOT NULL,
  `recommended_by` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `recommende_by_idx` (`recommended_by` ASC) VISIBLE,
  CONSTRAINT `recommende_by`
    FOREIGN KEY (`recommended_by`)
    REFERENCES `mydb`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emploee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emploee` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sale_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sale_detail` (
  `id` INT NOT NULL,
  `Customers_id` INT NOT NULL,
  `glasses_id` INT NOT NULL,
  `emploee_id` INT NOT NULL,
  INDEX `fk_Customers_has_glasses_glasses1_idx` (`glasses_id` ASC) VISIBLE,
  INDEX `fk_Customers_has_glasses_Customers1_idx` (`Customers_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `emploee_id_idx` (`emploee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_has_glasses_Customers1`
    FOREIGN KEY (`Customers_id`)
    REFERENCES `mydb`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customers_has_glasses_glasses1`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `mydb`.`glasses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emploee_id`
    FOREIGN KEY (`emploee_id`)
    REFERENCES `mydb`.`emploee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
