-- MySQL Script generated by MySQL Workbench
-- Wed Dec 18 21:39:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Providence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Providence` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Locality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Locality` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Providence_id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Providence_id_idx` (`Providence_id` ASC) VISIBLE,
  CONSTRAINT `Providence_id`
    FOREIGN KEY (`Providence_id`)
    REFERENCES `mydb`.`Providence` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Postal_code` INT NOT NULL,
  `Locality_id` INT NOT NULL,
  `Phone` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `Locality_id_idx` (`Locality_id` ASC) VISIBLE,
  CONSTRAINT `Locality_id`
    FOREIGN KEY (`Locality_id`)
    REFERENCES `mydb`.`Locality` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Store` (
  `Id` INT NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Postal code` INT NOT NULL,
  `Locality` VARCHAR(45) NOT NULL,
  `Providence` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `Id` INT NOT NULL,
  `Customer_id` INT NOT NULL,
  `Date_hour` DATETIME NOT NULL,
  `Eathere_Takeaway` VARCHAR(45) NOT NULL,
  `Amount` INT NOT NULL,
  `Total_price` DOUBLE NOT NULL,
  `Store_id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `Customer_id_idx` (`Customer_id` ASC) VISIBLE,
  INDEX `Store_id_idx` (`Store_id` ASC) VISIBLE,
  CONSTRAINT `Customer_id`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `mydb`.`Customer` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Store_id`
    FOREIGN KEY (`Store_id`)
    REFERENCES `mydb`.`Store` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizza_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizza_Category` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Image` VARCHAR(45) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Pizza_type` INT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `Pizza_type_idx` (`Pizza_type` ASC) VISIBLE,
  CONSTRAINT `Pizza_type`
    FOREIGN KEY (`Pizza_type`)
    REFERENCES `mydb`.`Pizza_Category` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_detail` (
  `Id` INT NOT NULL,
  `Order_Id` INT NOT NULL,
  `Product_Id` INT NOT NULL,
  `Date_hour_delivery` DATETIME NULL,
  INDEX `fk_Order_has_Product_Product1_idx` (`Product_Id` ASC) VISIBLE,
  INDEX `fk_Order_has_Product_Order1_idx` (`Order_Id` ASC) VISIBLE,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_has_Product_Order1`
    FOREIGN KEY (`Order_Id`)
    REFERENCES `mydb`.`Order` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Product_Product1`
    FOREIGN KEY (`Product_Id`)
    REFERENCES `mydb`.`Product` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surename` VARCHAR(45) NOT NULL,
  `Nif` INT NOT NULL,
  `Phone` INT NOT NULL,
  `Store_id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `Nif_UNIQUE` (`Nif` ASC) VISIBLE,
  UNIQUE INDEX `Phone_UNIQUE` (`Phone` ASC) VISIBLE,
  INDEX `Store_id_idx` (`Store_id` ASC) VISIBLE,
  CONSTRAINT `Store_id`
    FOREIGN KEY (`Store_id`)
    REFERENCES `mydb`.`Store` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
